# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: newproject

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: step1 - Checkout main branch from github
    - uses: actions/checkout@v3
    
    
    - name: Step2 - Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: step3 - github action to build Maven project
      run: mvn -B package --file pom.xml
      
    - name: step4 - list the current directory
      run: ls -a

    - name: step5 - my target file
      run: 
        cd target
        ls -a


